### ISSUE TITLE
Memory access error in test-transportsolver

### ISSUE THREAD

**Issue by bluescarni** [opengm/opengm#440]
clang's memory sanitizer gives the following output when run on ``test-transportsolver``:

```console
=================================================================
==25427==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000b5d8 at pc 0x000000523bc9 bp 0x7ffd56f9d0d0 sp 0x7ffd56f9d0c8
READ of size 8 at 0x60300000b5d8 thread T0
    #0 0x523bc8 in std::greater<double>::operator()(double const&, double const&) const /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_function.h:362:16
    #1 0x523b41 in std::binder2nd<std::greater<double> >::operator()(double const&) const /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/backward/binders.h:154:16
    #2 0x523a5b in bool __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::greater<double> > >::operator()<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/predefined_ops.h:231:16
    #3 0x5235e0 in std::iterator_traits<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > >::difference_type std::__count_if<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::greater<double> > > >(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__ops::_Iter_pred<std::binder2nd<std::greater<double> > >) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_algo.h:3193:6
    #4 0x5226b3 in std::iterator_traits<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > >::difference_type std::count_if<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, std::binder2nd<std::greater<double> > >(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, std::binder2nd<std::greater<double> >) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_algo.h:3979:14
    #5 0x53f7a6 in double TransportSolver::TransportationSolver<opengm::Maximizer, TransportSolver::MatrixWrapper<double> >::_FilterBound<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, unsigned long, std::vector<double, std::allocator<double> >&, std::vector<unsigned long, std::allocator<unsigned long> >*, double) /home/yardbird/repos/opengm/include/opengm/inference/auxiliary/transportationsolver.hxx:1058:31
    #6 0x53eda9 in double TransportSolver::TransportationSolver<opengm::Maximizer, TransportSolver::MatrixWrapper<double> >::Solve<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > >) /home/yardbird/repos/opengm/include/opengm/inference/auxiliary/transportationsolver.hxx:1110:2
    #7 0x50e8c8 in bool solveTest<TransportSolver::TransportationSolver<opengm::Maximizer, TransportSolver::MatrixWrapper<double> >, std::vector<double, std::allocator<double> > >(TransportSolver::TransportationSolver<opengm::Maximizer, TransportSolver::MatrixWrapper<double> >&, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > const&, double, double) /home/yardbird/repos/opengm/src/unittest/test_transportsolver.cpp:110:14
    #8 0x502832 in test_TransportationSolver_max() /home/yardbird/repos/opengm/src/unittest/test_transportsolver.cpp:215:3
    #9 0x50d08f in main /home/yardbird/repos/opengm/src/unittest/test_transportsolver.cpp:750:2
    #10 0x7fad135af61f in __libc_start_main (/lib64/libc.so.6+0x2061f)
    #11 0x4337a8 in _start (/home/yardbird/repos/opengm/build_clang/src/unittest/test-transportsolver+0x4337a8)

0x60300000b5d8 is located 0 bytes to the right of 24-byte region [0x60300000b5c0,0x60300000b5d8)
allocated by thread T0 here:
    #0 0x4faa10 in operator new(unsigned long) /var/tmp/portage/sys-devel/llvm-3.7.1/work/llvm-3.7.1.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:62
    #1 0x5104eb in __gnu_cxx::new_allocator<double>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/ext/new_allocator.h:104:27
    #2 0x51048b in __gnu_cxx::__alloc_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/ext/alloc_traits.h:182:14
    #3 0x510432 in std::_Vector_base<double, std::allocator<double> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:170:20
    #4 0x5102ae in std::_Vector_base<double, std::allocator<double> >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:185:27
    #5 0x50fa33 in std::_Vector_base<double, std::allocator<double> >::_Vector_base(unsigned long, std::allocator<double> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:136:9
    #6 0x50d83e in std::vector<double, std::allocator<double> >::vector(unsigned long, double const&, std::allocator<double> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:305:9
    #7 0x501e26 in test_TransportationSolver_max() /home/yardbird/repos/opengm/src/unittest/test_transportsolver.cpp:201:18
    #8 0x50d08f in main /home/yardbird/repos/opengm/src/unittest/test_transportsolver.cpp:750:2
    #9 0x7fad135af61f in __libc_start_main (/lib64/libc.so.6+0x2061f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_function.h:362:16 in std::greater<double>::operator()(double const&, double const&) const
Shadow bytes around the buggy address:
  0x0c067fff9660: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff9670: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff9680: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c067fff9690: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff96a0: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
=>0x0c067fff96b0: fa fa 00 00 00 00 fa fa 00 00 00[fa]fa fa fd fd
  0x0c067fff96c0: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff96d0: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff96e0: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c067fff96f0: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff9700: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25427==ABORTING
```

@DerThorsten you mentioned someone who might be knowledgeable about this specific piece of code, maybe we should ping him/her?

**Comment by DerThorsten** [comment]
@homul do you might know whats going on?
